### PR TITLE
Ignore nullability in struct types

### PR DESCRIPTION
**Pull request by AntonDeMeester**

### CODE REVIEW

**Comment by naomigl** [comment]
Checked methods and testing and seems good! Great job!

**Comment by gdahia** [comment]
Are there plans to merge this and release a new version of `chispa`? We just encountered a situation in which this feature would  come in handy.

**Comment by AntonDeMeester** [comment]
@MrPowers

**Comment by sharon-rozinsky** [comment]
Any update on when this might be pushed to the next version? This is a really critical feature

**Comment by MrPowers** [comment]
@AntonDeMeester - sorry for the delay getting this merged.  I just merged and did a release.  Can you please do some testing and make sure it's all working as expected?  It's version 0.9.0.

cc: @sharon-rozinsky @naomigl

**Comment by AntonDeMeester** [comment]
@MrPowers I don't work on the project I needed this anymore 😂 
@sharon-rozinsky Can you check this?

**Comment by sharon-rozinsky** [comment]
@MrPowers @AntonDeMeester I have tested the new code by calling `assert_df_equality` with `ignore_schema=True` and it works as expected.
Thanks for this important update!

**Comment by MrPowers** [comment]
Great @sharon-rozinsky , thanks for checking!

**Pull request merged**
