### PR TITLE
Ignore nullability for nested array types

### PR DESCRIPTION
**Pull request by chris-remedy**

### CODE REVIEW

**Comment by MrPowers** [comment]
Thanks for this contribution.  Ignoring nullability for nested array types seems important.

Looks like your PR deletes the `are_structfields_equal` method, which is part of the public interface.  Is there any way we can implement this functionality without changing the public interface?  I don't want to remove a method from this library that users are probably depending on (cause the the next release of chispa will break their code).  Let me know your thoughts.

**Comment by chris-remedy** [comment]
Oh, sorry, I didn't realize that was intended to be public. How's this version look? I put `are_structfields_equal_ignore_nullable` in `schema_comparer` because it depends circularly on `are_datatypes_equal_ignore_nullable`.

**Comment by MrPowers** [comment]
@chris-remedy - thanks for the quick response.  Look like you're proposing having `are_structfields_equal_ignore_nullable(sf1, sf2)` in the schema_comparer.py file and `are_structfields_equal(sf1, sf2, ignore_nullability=False)` in the structfield_comparer.py file.

If I understand correctly, `are_structfields_equal` has a bug, so `are_structfields_equal(sf1, sf2, ignore_nullability=True)` doesn't work properly for nested arrays.  Can we just fix the existing function?

I'm hesitant to have `are_structfields_equal_ignore_nullable` in one file and `are_structfields_equal` in another file.  I'd also like to have just one function because it seems like they're doing the same thing.

Sorry for being picky here.  I was looking at the PyPi download stats the other day and was surprised to find a lot of organizations depending on this lib.  That's why I'm being really careful to make sure all changes are 100% backwards compatible.  Thanks, we're getting closer!

**Comment by chris-remedy** [comment]
The problem is that in order to operate recursively on arrays, we need a function that can compare DataTypes, not StructFields.

Previously, both `check_type_equal_ignore_nullable` and `are_structfields_equal` were comparing two StructFields, and both failed to correctly explore deeply nested values (although I think the two behaved differently with regard to arrays).

I agree it would be ideal to only have one function for comparing structfields, but I'm not sure how to do that while maintaining backwards compatibility with the current layout of things being split between two files.

**Comment by chris-remedy** [comment]
Is this better?

**Comment by cfdair** [comment]
Any updates on this one?

**Comment by MrPowers** [comment]
@robertkossendey @orcascope - can you look at this PR if you have a sec?

**Comment by orcascope** [comment]
Looks good. @MrPowers

**Comment by robertkossendey** [comment]
@MrPowers LGTM

**Comment by MrPowers** [comment]
Thanks for the contribution @chris-remedy.  Sorry for taking so long to merge this.

Thank you for reviewing @orcascope and @robertkossendey.  Really appreciate everyone's help.

**Pull request merged**
