### PR TITLE
feat: NOTICE-binary file

### LINKED ISSUE #116: feat: Create NOTICE file
**Is your feature request related to a problem? Please describe.**

Terms of usage some of chispa's dependencies require adding a notice. A good example is `prettytable`: [required notice](https://github.com/jazzband/prettytable?tab=License-1-ov-file#readme)

**Describe the solution you would like**

1. Create a file `NOTICE-binary.md`
2. Start filling this file with notices from 3d-party dependencies

**Additional context**
.

**Are you planning on creating a PR?**

- [x] I'm planning to make a pull-request

### PR DESCRIPTION
**Pull request by SemyonSinchenko**
**PR Checklist**

- [x] A description of the changes is added to the description of this PR.
- [x] If there is a related issue, make sure it is linked to this PR.
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added or modified a feature, documentation in `docs` is updated

**Description of changes**

We need to follow licenses of our dependencies little more strictly. I'm not 100% sure how to do it, but I think adding NOTICE-binary is a good first step.

Close #116

### CODE REVIEW

**Comment by SemyonSinchenko** [comment]
@fpgmaas Do you have an idea, how can we include this file into an output python package? Based on my knowledge, we must distribute it with the chispa itself.

**Comment by fpgmaas** [comment]
> @fpgmaas Do you have an idea, how can we include this file into an output python package? Based on my knowledge, we must distribute it with the chispa itself.

@SemyonSinchenko I think we can use Poetry's `include`, I did something similar [here](https://github.com/fpgmaas/cookiecutter-poetry/blob/a7682be15043034d7216273907044038510dace3/pyproject.toml#L13)

**Comment by fpgmaas** [comment]
@SemyonSinchenko I don't think we need this though, right? We don't distribute a copy of these packages ourselves. We just mention that our package needs these packages. These are then installed by the user from PyPI, and that includes the license. Do you know any other big OS projects that do this?

**Comment by SemyonSinchenko** [comment]
> @SemyonSinchenko I don't think we need this though, right? We don't distribute a copy of these packages ourselves. We just mention that our package needs these packages. These are then installed by the user from PyPI, and that includes the license. Do you know any other big OS projects that do this?

I do not know to be honest... You are right, let's leave it as is, just a NOTICE file.

**Pull request merged**
